### ISSUE TITLE
What is the Definition for LoC?

### ISSUE THREAD

**Issue by thomashzhang** [RefactoringCombos/ArlosCommitNotation#12]
Hello,

Love this so far! But what is the definition for LoC? Is this "line of code"? I think so, but it's not too common of an acronym (I didn't know at first). Would love to have it in the documentation. Let me know if you need someone else to make a PR.

Thanks!

**Comment by arlobelshee** [comment]
Just created #13 to address this.

**Comment by arlobelshee** [comment]
Merged PR. Closing as fixed.
