### ISSUE TITLE
`R` and recipes

### ISSUE THREAD

**Issue by JayBazuzi** [RefactoringCombos/ArlosCommitNotation#14]
Why does `R` require:

> You followed the published recipe, including running full-suite test runs when indicated.

?

Wouldn't a recipe give you `r`?

**Comment by arlobelshee** [comment]
Well, I'm meaning the recipes from Fowler. The ones for which proof rests on tests, not static analysis.

How can we make that clear?

**Comment by JayBazuzi** [comment]
I don't think "proof" is the right word here. Check? Verify? Not sure if changing that would help, though.

**Comment by arlobelshee** [comment]
I believe this is addressed in the current version, with more clarity about the distinction between "Provable refactorings" "Test-supported procedural refactorings" and "general remodeling". I'm going to close this as fixed. Let me know if you think I should re-open.
