### ISSUE TITLE
Are we optimizing for typing or readability?

### ISSUE THREAD

**Issue by rogerdubbs** [RefactoringCombos/ArlosCommitNotation#20]
I tried this and my reviewer gave this feedback.

Also: "i really don't want to have to go to a legend to see what these mean"

I get that this notation can be learned but wanted to pass along the feedback.

**Comment by JayBazuzi** [comment]
If you're committing every 30 seconds, anything more than `r` is annoying to type.

In a gnarly slow build, `REFACTOR:ReSharper - Extract Method` is fine to type.

**Comment by arlobelshee** [comment]
I also find the one-letter codes improve readability after they are consistent. There is a 4-char column at the left of the commit long. You can vertically scan it to review risk. I find that much easier to read than if we used words and I had to actually read / interpret each line independently.
